//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SliderBannerProject.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Slider
    {
        public int ID { get; set; }
        public string SliderPhoto { get; set; }
        public string SliderInfo1 { get; set; }
    }
}
